spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: rentalcars
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  mail:
    host: smtp.gmail.com
    username: www.pixel93@gmail.com
    password: huguhxptywqqljzu
    port: 587
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
      ssl.trust: smtp.gmail.com
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/projectBase"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    url: "jdbc:postgresql://localhost:5432/projectBase"
server:
  port: 8085

---

jwt:
  secret: qwepuisdhfaksdjflsdfn747477_____**
  expiration: 6000000